package sbatch

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/hpc-gridware/slurm-shim/internal/config"
)

// resolveGeometry derives the SLURM task geometry from the parsed options,
// applying SLURM's defaults: -N without -n/--ntasks-per-node is one task per
// node; --ntasks wins over an inconsistent --ntasks-per-node.
func (o options) resolveGeometry() (ntasks, cpusPerTask int) {
	cpusPerTask = o.cpusPerTask
	if cpusPerTask < 1 {
		cpusPerTask = 1
	}
	switch {
	case o.haveNtasks:
		ntasks = o.ntasks
	case o.nodes > 0 && o.havePerNode:
		ntasks = o.nodes * o.ntasksPerNode
	case o.nodes > 0:
		ntasks = o.nodes
	case o.havePerNode:
		ntasks = o.ntasksPerNode
	default:
		ntasks = 1
	}
	if ntasks < 1 {
		ntasks = 1
	}
	return ntasks, cpusPerTask
}

// computeSlots applies the partition's slots rule (REQ-SBT-002), the inverse of
// task policy N3. A literal integer pins the slot count; "per-task" (and the
// empty default) multiplies ntasks by cpus_per_task.
func computeSlots(opt options, part config.Partition) (int, error) {
	ntasks, cpt := opt.resolveGeometry()
	rule := strings.TrimSpace(part.Slots)
	switch rule {
	case "", "per-task":
		return ntasks * cpt, nil
	default:
		n, err := strconv.Atoi(rule)
		if err != nil {
			return 0, fmt.Errorf("sbatch: error: partition slots rule %q is neither an integer nor \"per-task\"", rule)
		}
		return n, nil
	}
}

// parseJobID extracts the base job id from qsub -terse output. A plain job
// prints "<id>"; an array job prints "<id>.<first>-<last>:<step>" (REQ-SBT-003).
func parseJobID(terse string) string {
	s := strings.TrimSpace(terse)
	if s == "" {
		return ""
	}
	s = strings.SplitN(s, "\n", 2)[0]
	return strings.SplitN(s, ".", 2)[0]
}

// buildQsubArgs assembles the qsub argv (without the trailing script + args).
// -terse yields just the job id on stdout (REQ-SBT-003).
func buildQsubArgs(opt options, part config.Partition, slots int) []string {
	args := []string{"-terse", "-q", part.Queue, "-pe", part.PE, strconv.Itoa(slots)}
	if opt.jobName != "" {
		args = append(args, "-N", opt.jobName)
	}
	if opt.output != "" {
		args = append(args, "-o", opt.output)
	}
	if opt.errorPath != "" {
		args = append(args, "-e", opt.errorPath)
	}
	if opt.chdir != "" {
		args = append(args, "-wd", opt.chdir)
	}
	return args
}

// buildWrapper generates the wrapper-mode bash script (SI-57, REQ-SBT-004): it
// evaluates the fabricator's exported environment, then execs the stored
// original script verbatim so its shebang and argv survive untouched. Paths are
// single-quote-escaped so a name containing a quote cannot break out.
func buildWrapper(shimPath, storedScript string) string {
	return "#!/bin/bash\n" +
		"# Generated by slurm-shim sbatch (wrapper mode, SI-57). Do not edit.\n" +
		"eval \"$(" + shellQuote(shimPath) + " slurm-shim-env --export)\"\n" +
		"exec " + shellQuote(storedScript) + " \"$@\"\n"
}

// shellQuote wraps a value in single quotes, replacing each embedded quote with
// the POSIX-safe sequence quote-backslash-quote-quote.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
